{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "manifest-merger",
    "version": "30.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "manifest-merger-30.0.2.jar",
          "url": "manifest-merger-30.0.2.jar",
          "size": 206458,
          "sha512": "50029d157e15b3f817d731a2cff28ca8835127565c61aaafefd93655367a531522422649c8c9133c4b45078f3c6970df1420ab5f26fa88517cc8f867ba09246c",
          "sha256": "194aca3ac97605e4b07cefcd8289bb5e27dc7a80eb33059bebd352d8ed922737",
          "sha1": "84cba9f61ce9b547b2e836efc32ccb3febaf21c4",
          "md5": "e07ba91794ed5ec82981d1afb2f512c7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.0.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "30.0.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "30.0.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "net.sf.kxml",
          "module": "kxml2",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "manifest-merger-30.0.2.jar",
          "url": "manifest-merger-30.0.2.jar",
          "size": 206458,
          "sha512": "50029d157e15b3f817d731a2cff28ca8835127565c61aaafefd93655367a531522422649c8c9133c4b45078f3c6970df1420ab5f26fa88517cc8f867ba09246c",
          "sha256": "194aca3ac97605e4b07cefcd8289bb5e27dc7a80eb33059bebd352d8ed922737",
          "sha1": "84cba9f61ce9b547b2e836efc32ccb3febaf21c4",
          "md5": "e07ba91794ed5ec82981d1afb2f512c7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "manifest-merger-30.0.2-javadoc.jar",
          "url": "manifest-merger-30.0.2-javadoc.jar",
          "size": 579834,
          "sha512": "4ddad0281a9576ab3386168cddd46c361b3c46b85ed20321beca47cd7d0abcf5abf8c6e8a701a27d86a9a769324d9b68b59c1ce9dc575ebf31571eb2039e733b",
          "sha256": "ec44dd497f0500d276a89be11d847b38e9de5eaed70182385b7e8ffb5136d935",
          "sha1": "f029d7a56369dd5ee3c93af6b9d3ea90a8e46c6e",
          "md5": "e347796ef465bdaddce93384731b9afa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "manifest-merger-30.0.2-sources.jar",
          "url": "manifest-merger-30.0.2-sources.jar",
          "size": 207971,
          "sha512": "34535c93f9537d2a4e3354d9a383d35da28f923f9a6beff1146a5259258fed6a36f65f0acae8bfecbaa91945be9ff41091ca07e6020b8ad271efb2ac281e6f14",
          "sha256": "2a333236d79a914ce153be41c43faebcc5199c6f7f66194d8b8f1d1db05e2c90",
          "sha1": "476b89cf093cdc800493efeac1779c99b3b955cf",
          "md5": "5c8e9fdcfc73ac5a7d19e2a0b14356b3"
        }
      ]
    }
  ]
}
