{
  "formatVersion": "1.1",
  "component": {
    "group": "io.perfmark",
    "module": "perfmark-api",
    "version": "0.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 6,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "perfmark-api-0.25.0.jar",
          "url": "perfmark-api-0.25.0.jar",
          "size": 6730,
          "sha512": "c9f4fed240e56db150d178a26ce0836c9efc223c77054e57e429d55296987b971a93a2af0a351856442123857694019eeb85648d892abec3f9c4c0d850e51bb2",
          "sha256": "2044542933fcdf40ad18441bec37646d150c491871157f288847e29cb81de4cb",
          "sha1": "340a0c3d81cdcd9ecd7dc2ae00fb2633b469b157",
          "md5": "6860016b29a2dc46de730bfb7c750a23"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 6,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "perfmark-api-0.25.0.jar",
          "url": "perfmark-api-0.25.0.jar",
          "size": 6730,
          "sha512": "c9f4fed240e56db150d178a26ce0836c9efc223c77054e57e429d55296987b971a93a2af0a351856442123857694019eeb85648d892abec3f9c4c0d850e51bb2",
          "sha256": "2044542933fcdf40ad18441bec37646d150c491871157f288847e29cb81de4cb",
          "sha1": "340a0c3d81cdcd9ecd7dc2ae00fb2633b469b157",
          "md5": "6860016b29a2dc46de730bfb7c750a23"
        }
      ]
    }
  ]
}
