{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-ui",
    "version": "2.7.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.drawerlayout",
          "module": "drawerlayout",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.7.6"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0-beta01"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-ui-2.7.6.aar",
          "url": "navigation-ui-2.7.6.aar",
          "size": 91131,
          "sha512": "4b2fbf130be657365e8784c35def30ebec19a1f83885fc7d20077d3af87366497fb05b787d4b544734b9000e89286c10283fbe8e77c07e0159cfbc77cef62974",
          "sha256": "98266e16ca8ce32cd1c12c9519877f689eb8c7285ca1dc895ed1f16597dc7fed",
          "sha1": "54ad3df0b40a3ccf1ecf2976063ff4e95d5e2efa",
          "md5": "9fc2ef2b8c0a0a2b92a3bd6e2c2d7833"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.drawerlayout",
          "module": "drawerlayout",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.7.6"
          }
        },
        {
          "group": "androidx.transition",
          "module": "transition",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0-beta01"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-ui-2.7.6.aar",
          "url": "navigation-ui-2.7.6.aar",
          "size": 91131,
          "sha512": "4b2fbf130be657365e8784c35def30ebec19a1f83885fc7d20077d3af87366497fb05b787d4b544734b9000e89286c10283fbe8e77c07e0159cfbc77cef62974",
          "sha256": "98266e16ca8ce32cd1c12c9519877f689eb8c7285ca1dc895ed1f16597dc7fed",
          "sha1": "54ad3df0b40a3ccf1ecf2976063ff4e95d5e2efa",
          "md5": "9fc2ef2b8c0a0a2b92a3bd6e2c2d7833"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-ui-2.7.6-sources.jar",
          "url": "navigation-ui-2.7.6-sources.jar",
          "size": 20795,
          "sha512": "49ec2f26812e974c0bf50c34ece9bd4b50f61d849a776c6aff661ecd9866130d1f1af91dc0d2faa0f55c961b3dc325e6f372fdd63748d57fd19c5a8fcbb755b7",
          "sha256": "685739df6ad0c60e77aa5a7ceafd9631aa4d02a5cc452f85f7c3120155f61ece",
          "sha1": "23473de85ea8510077e13d7f33fd0b107331afed",
          "md5": "8d276759dbd1c8a07bbd9fb21f3e3049"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-ui is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-ui-2.7.6-versionMetadata.json",
          "url": "navigation-ui-2.7.6-versionMetadata.json",
          "size": 10087,
          "sha512": "370d68eb8362959b9b1b211d78eb714b870679b6f335b9814deec6415b691223a754a871a4c6d2350f6e67e8b76ed85afbc80bc64b6021692fe442ec6bc78c13",
          "sha256": "f0ac40e381daf5f57b29b7c39c275f7d1f7e2fb1cba88bbbed797e79284840e2",
          "sha1": "8746cd5277c85287d39d2c68e056653ae2dbcadc",
          "md5": "70874962a572d1de4719a3aa66690114"
        }
      ]
    }
  ]
}